### ISSUE TITLE
How to position the marker at a specific lng/lat value?

### ISSUE THREAD

**Issue by invaders-xx** [humaidem/filament-map-picker#2]
Is there a way to position a marker at a specific lng/lat if the lng/lat are not stored as POINT but string ?

**Comment by tumapav** [comment]
I believe you can use `afterStateHydrated()` to customize how is your string format converted into lat, lng array used by the map picker. Try placing the string to lat,lng array parser into this function.

**Comment by invaders-xx** [comment]
Thanks
